---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: version
  - name: unpacked-artifacts

outputs:
  - name: tarball

params:
  ARTIFACT_NAME: application

run:
  path: sh
  args:
    - -exc
    - |
      VERSION=$(cat version/version)
      cd unpacked-artifacts 
      tar -czvf ../tarball/${ARTIFACT_NAME}-${VERSION}.tgz . 
      cd - 